#!/usr/bin/env ruby

## style.css generator script

## space is in pixel
@banner_color = "#D0D0D0"
@text_color = "rgb(64, 64, 64);"
@left_banner_width = 130
@cross_margin = 40
@heading_color = "rgb(225, 110, 52)"

@style = "/* AUTOGENERATED DON'T EDIT  */

ul.no-bullet { list-style: none; }

ul.publist li { margin-top: 0.5em; }

div.navigation { 
	float: left;
	position: relative; 
	top: 99px; 
	width: #{@left_banner_width}px;
	min-height: 400px;
	margin-left: #{- (@left_banner_width + @cross_margin)}px;
	padding-top: 10px;
	padding-bottom: 20px;
	padding-left: 20px;
	color:transparent; 
	background: #{@banner_color}; }

div.navigation div { 
	margin-top: 0.15em; }


div.navigation > div.home { 
  	margin-bottom: 0.4em; }

div.submenu div { 
	margin-left: 15px;
	font-size: small; }

a.plain { text-decoration: none; }

a.current { 
	font-weight: bold; }

a:link {
	color: #{@text_color};
	background: transparent; }

a:active {
	color: #{@text_color};
	background: transparent; }

a:visited {
	color: #{@text_color};
	background: transparent; }

a:hover {
	color: white;
	background: #{@text_color}; }

/* ⇗ from http://www.alanwood.net/unicode/arrows.html */ 
a[rel='external']:after {
	content: \"\\21D7\";
	font-weight: bold;
	padding-left: 0.2em; }

a.plain:after, div.navigation a:after, div.copyright a:after {
	content: ''; }

.title a:hover {
	text-decoration: none;
	background: transparent; }


img.logoimage1 {
  width: 90px; }

div.logo1 {
	position: absolute; 
	top: -100px; 
	left: 35px; }

div.logo2 {
	position: relative;
	padding: 10px;
	padding-top: 20px;
	width: 100px;
	text-align: left; }

div.logo1 a:hover, div.logo2 a:hover {
	background: transparent;}

body {
	width: 750px; /* width of main body */ 
	font-family: Arial, sans-serif;
	font-size: medium;
	color: #{@text_color};
	background-color: white;
	margin-top: 20px; /* whitespace on top */ 
	margin-left: auto;
	margin-right: auto;
	padding-left: #{(@left_banner_width + @cross_margin)}px; }

h1 {
	font-family: Arial, sans-serif;
	font-size: x-large;
	font-weight: bold;
	color: #{@heading_color}; }

h2 {
	font-family: Arial, sans-serif;
	font-size: large;
	font-weight: bold;
	color: #{@heading_color}; }

h3 {
	font-family: Arial, sans-serif;
	font-size: medium;
	font-weight: bold;
	color: #{@heading_color}; }

img {
	border: 0; }

td.people {
	vertical-align: top; }

div.important {
	border: solid #{@heading_color}; }

div.copyright {
	font-family: Arial, sans-serif;
	font-size: small;
	color: #{@text_color}; }

div.banner {
	background: #{@banner_color};
	width: 100%;
	height: 68px;
	font-family: Arial, sans-serif;
	color: #{@text_color};
	text-align: center;
	padding-top: 10px;
	margin-bottom: 20px; }

div.banner1 {
	font-size: xx-large;
	font-weight: bold; }

div.banner2 {
	font-size: large;
	font-weight: bold; }

/* for centered banners */
div.banner3 {
  padding-top: 10px;
	font-size: xx-large;
	font-weight: bold; }

span.paper-title, span.coloredemph {
	color: #{@heading_color};
	font-style: italic; }

span.colored {
  	color: #{@heading_color}; }

span.name {
	color: #{@heading_color};
	font-weight: bold; }

span.small {
	font-size: small; }

span.strong {
	font-weight: bold; }

span.emph {
	font-style: italic; }

div.photos img {
	padding: 6px; }

div.photos a:hover {
	background: transparent; }

a.imagelink img {
  width: 180px;

}

a.imagelink {
  background: transparent; 
}

a.imagelink:hover{
  background: transparent; 
}

table.examples td {
  vertical-align: top;
  padding: 10px;
}

"
# border colors
"
a.imagelink img{
  border: 2px;
  border-style: solid;
  border-color: gray;
  background: transparent; 
}

a.imagelink:hover img{
  border: 2px;
  border-style:solid;
  border-color: #{@text_color};
}
"



File.open("style.css", "w") { |file|
  file.write(@style)
}
